---
# consul/tasks/main.yml
# https://www.digitalocean.com/community/tutorial_series/getting-started-with-consul

- name: consul configuration directory exists
  file:
    path: /usr/local/etc/consul.d
    state: directory

- name: consul configuration file exists
  notify: restart consul
  template:
    src: cluster.json.j2
    dest: /usr/local/etc/consul.d/cluster.json
    owner: consul
    group: consul
    mode: "0600"
