---
# roles/ldap/tasks/main.yml

- name: ensure {{ item }} exists
  file:
    path: "/{{ item }}"
    state: directory
    owner: ldap
    group: ldap
  loop:
    - "{{ ldap_etc_dir }}"
    - "{{ ldap_etc_dir }}/slapd.d"

- name: Copy ldap client configuration
  template:
    backup: yes
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: ldap
    group: ldap
    mode: "0644"
  loop:
    - "{{ ldap_etc_dir }}/ldap.conf"
    - "{{ ldap_etc_dir }}/users.ldif"

- name: ldap server configuration copy
  template:
    backup: yes
    src: "{{ ldap_etc_dir }}/slapd.ldif"
    dest: "/{{ ldap_etc_dir }}/slapd.ldif"
    owner: ldap
    group: ldap
    mode: "0640"
  notify: slapd restart

- name: configure {{ ldap_etc_dir }}/slapd.d contents
  command: slapadd -n0 -F /{{ ldap_etc_dir }}/slapd.d -l /{{ ldap_etc_dir }}
  args:
    creates: "/{{ ldap_etc_dir }}/slapd.d/cn=config.ldif"
  notify: slapd restart
