---
# freebsd/handlers/main.yml

- name: restart sysctl
  service:
    name: sysctl
    state: restarted

- name: restart network
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - netif
    - routing

- name: "restart {{ freebsd_service }}"
  service:
    name: "{{ freebsd_service }}"
    state: restarted
