freebsd_packages:
  - bhyve-firmware
  - gtar
  - screen
  - tmux
  - xauth

freebsd_network:
  # autobridge_bridge0: tap?
  # autobridge_interfaces: bridge0
  # cloned_interfaces: bridge0
  # ifconfig_bridge0: addm em0
  ifconfig_em0: inet 192.168.1.4 netmask 255.255.255.0
  ifconfig_em0_alias0: inet 192.168.1.10-19

freebsd_sysctls:
  kern.vt.enable_bell: 0
  net.link.tap.up_on_open: 1
  security.jail.sysvipc_allowed: 1

jailer_base_snapshot: 1
jailer_dataset: zdata/jails
jailer_distsite: ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/12.2-RELEASE
jailer_mountpoint: /jails

zfs_pools:
  - device: /dev/ada0
    mountpoint: /data
    name: zdata
